services:
  - type: web
    name: howmuchdoesthisweigh-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    runtime: node
    nodeVersion: 18
    autoDeploy: true
